server:
  port: 8083
spring:
  application:
    name: common-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

---
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
